config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'wallets/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "wallets#index"

  resources :wallets do
    resources :transactions
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :wallet_details
  validates :title, presence: true, length: { minimum: 3 }
  delegate :user_wallets, :team_wallets, :stock_wallets, to: :wallet_details

end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallet = Wallet.where(user_id: current_user[:id]).first
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/index.html.erb
<h3 style="padding-bottom: 30px; text-transform: capitalize"><%= @wallet.title %>s</h3>
<div class="row justify-content-center" >
  <div class="col-md-4 col-lg-4">
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h5 class="card-title card-title-shadow">User Wallet</h5>
        <p class="card-text">
        <div>
          <span>Wallet Balance: </span><strong><%=number_to_currency  @wallet.user_wallets.first[:balance] %></strong><br>
          <span>Transaction Balance: </span><strong><%=number_to_currency  @wallet.user_wallets.first.balance_from_transactions %></strong><br>
          <%= link_to "Transaction details...", wallet_transactions_path(@wallet, role: "u")  %> </div>
        <hr>
        </p>
        <%= link_to "Deposit", new_wallet_transaction_path(@wallet, role: "u", tran_type: "deposit"), :class => "btn btn-primary"  %>
        <%= link_to "Transfer", new_wallet_transaction_path(@wallet, role: "u", tran_type: "transfer"), :class => "btn btn-primary"  %>
        <%= link_to "Withdraw", new_wallet_transaction_path(@wallet, role: "u", tran_type: "withdraw"), :class => "btn btn-primary"  %>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-lg-4">
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h5 class="card-title card-title-shadow">Team Wallet</h5>
        <p class="card-text">
        <div>
          <span>Wallet Balance: </span><strong><%=number_to_currency  @wallet.team_wallets.first[:balance] %></strong><br>
          <span>Transaction Balance: </span><strong><%=number_to_currency  @wallet.team_wallets.first.balance_from_transactions %></strong><br>
          <%= link_to "Transaction details...", wallet_transactions_path(@wallet, role: "t")  %></div>
        <hr>
        </p>
        <%= link_to "Deposit", new_wallet_transaction_path(@wallet, role: "t", tran_type: "deposit"), :class => "btn btn-primary"  %>
        <%= link_to "Transfer", new_wallet_transaction_path(@wallet, role: "t", tran_type: "transfer"), :class => "btn btn-primary"  %>
        <%= link_to "Withdraw", new_wallet_transaction_path(@wallet, role: "t", tran_type: "withdraw"), :class => "btn btn-primary"  %>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-lg-4">
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h5 class="card-title card-title-shadow">Stock Wallet</h5>
        <p class="card-text">
        <div>
          <span>Wallet Balance: </span><strong><%=number_to_currency  @wallet.stock_wallets.first[:balance] %></strong><br>
          <span>Transaction Balance: </span><strong><%=number_to_currency  @wallet.stock_wallets.first.balance_from_transactions %></strong><br>
          <%= link_to "Transaction details...", wallet_transactions_path(@wallet, role: "s")  %></div>
        <hr>
        </p>
        <%= link_to "Deposit", new_wallet_transaction_path(@wallet, role: "s", tran_type: "deposit"), :class => "btn btn-primary"  %>
        <%= link_to "Transfer", new_wallet_transaction_path(@wallet, role: "s", tran_type: "transfer"), :class => "btn btn-primary"  %>
        <%= link_to "Withdraw", new_wallet_transaction_path(@wallet, role: "s", tran_type: "withdraw"), :class => "btn btn-primary"  %>
      </div>
    </div>
  </div>
</div>