config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'wallets/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "wallets#index"

  resources :wallets do
    resources :transactions
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @wallet = Wallet.find(params[:wallet_id])
    @name = get_wallet_name params[:role]
    case params[:role]
    when 'u'
      @transactions = Transaction.where("(sender_id = ? or receiver_id = ?)", @wallet.user_wallets.first[:id], @wallet.user_wallets.first[:id])
    when 't'
      @transactions = Transaction.where("(sender_id = ? or receiver_id = ?)", @wallet.team_wallets.first[:id], @wallet.team_wallets.first[:id])
    when 's'
      @transactions = Transaction.where("(sender_id = ? or receiver_id = ?)", @wallet.stock_wallets.first[:id], @wallet.stock_wallets.first[:id])
    end
  end

  def new
    @wallet = Wallet.find(params[:wallet_id])
    @role = params[:role]
    @tran_type = params[:tran_type]
    @name = get_wallet_name @role
    @balance = get_wallet_balance(@role, @wallet)
    @transaction = Transaction.new
    @wallet_details = @wallet.wallet_details
    case @tran_type
    when 'deposit'
      @action = "Deposit"
    when 'withdraw'
      @action = "Withdraw"
    when 'transfer'
      @action = "Transfer"
    end
  end

  def create
    @wallet = Wallet.find(params[:wallet_id])
    @role = params[:transaction][:role]
    @tran_type = params[:transaction][:tran_type]
    @name = get_wallet_name @role
    @wallet_detail = get_wallet_detail(@role, @wallet)
    @balance = get_wallet_balance(@role, @wallet)

    case @tran_type
    when 'deposit'
      @action = "Deposit"
      @transaction = Transaction.new(:amount => params[:transaction][:amount],:description => params[:transaction][:description],:sender_id => @wallet_detail[:id],:receiver_id => @wallet_detail[:id], :transaction_type => @action)
      if @transaction.save
        @wallet_detail.update(:balance => @wallet_detail.balance + params[:transaction][:amount].to_i)
        redirect_to wallets_path
      else
        render :new
      end

    when 'withdraw'
      @action = "Withdraw"
      @transaction = Transaction.new(:amount => params[:transaction][:amount],:description => params[:transaction][:description],:sender_id => @wallet_detail[:id],:receiver_id => @wallet_detail[:id], :transaction_type => @action)
      if(@wallet_detail.balance - params[:transaction][:amount].to_i >= 0)
        if @transaction.save
          @wallet_detail.update(:balance => @wallet_detail.balance - params[:transaction][:amount].to_i)
          redirect_to wallets_path
        else
          render :new
        end
      else
        render :new
      end

    when 'transfer'
      @action = "Transfer"
      @transaction = Transaction.new(:amount => params[:transaction][:amount],:description => params[:transaction][:description],:sender_id => @wallet_detail[:id],:receiver_id => params[:transaction][:receiver_id], :transaction_type => @action)
      if(@wallet_detail.balance - params[:transaction][:amount].to_i >= 0)
        if @transaction.save
          @wallet_detail.update(:balance => @wallet_detail.balance - params[:transaction][:amount].to_i)
          @receiver_wallet_detail = WalletDetail.find(params[:transaction][:receiver_id])
          @receiver_wallet_detail.update(:balance => @receiver_wallet_detail.balance + params[:transaction][:amount].to_i)
          redirect_to wallets_path
        else
          @wallet_details = @wallet.wallet_details;
          if(params[:transaction][:receiver_id].empty?)
            @transaction.errors.add(:receiver_id, :receiver_id, message: "is not selected")
          end
          render :new
        end
      else
        @wallet_details = @wallet.wallet_details;
        @transaction.errors.add(:amount, :amount, message: "is bigger than balance")
        render :new
      end

    end
  end

  private
  def get_wallet_name(short)
    if short == "u" then name = "User Wallet" end
    if short == "t" then name = "Team Wallet" end
    if short == "s" then name = "Stock Wallet" end
    name
  end
  def get_wallet_balance(short, wallet_to_get)
    if short == "u" then balance = wallet_to_get.user_wallets.first[:balance] end
    if short == "t" then balance = wallet_to_get.team_wallets.first[:balance] end
    if short == "s" then balance = wallet_to_get.stock_wallets.first[:balance] end
    balance
  end

  def get_wallet_detail(short, wallet_to_get)
    if short == "u" then wallet_detail = wallet_to_get.user_wallets.first end
    if short == "t" then wallet_detail = wallet_to_get.team_wallets.first end
    if short == "s" then wallet_detail = wallet_to_get.stock_wallets.first end
    wallet_detail
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<h3 class="mt-3">Transaction History of <%=@name %></h3>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th scope="col">Date</th>
    <th scope="col">Amount</th>
    <th scope="col">Type</th>
    <th scope="col">Description</th>

  </tr>
  </thead>
  <tbody>
  <% if !@transactions.nil? && @transactions.length > 0 %>
    <% @transactions.each do |trans| %>
      <tr>
        <th scope="row"><%= trans.created_at %></th>
        <td><%= number_to_currency trans.amount %></td>
        <td><%= trans.transaction_type %></td>
        <td><%= trans.description %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<% if @transactions.nil? || @transactions.length < 1 %>
  <h5 class="mt-5">There is no transaction, please deposit or transfer from another wallet by clicking <%link_to "deposit | transfer", wallet_path(@wallet) %></h5>
<% end %>

app/views/transactions/new.html.erb
<style>
    select {appearance: auto !important;}
</style>
<h3 style="padding-bottom: 30px; text-transform: capitalize"><%= "#{@action} #{@name}"  %></h3>
<div class="row justify-content-center" >
  <div class="col-md-4 col-lg-4">
    <%= form_with model: [@wallet, @transaction] do |form| %>
      <div class="form-group">
        <label for="transaction_balance">Balance</label> <br>
        <input value="<%= @balance %>" readonly="readonly" class="form-control" type="number" name="transaction[balance]" id="transaction_balance"> <br>
      </div>
      <%if @action == "Transfer" %>
        <div class="form-group">
          <%= form.label :receiver_id %><br />
          <%= form.collection_select :receiver_id, @wallet_details, :id, :wallet_name, {prompt: "Please select"}, autofocus:true, class: "form-control", id: "transaction_receiver_id" %>
          <% @transaction.errors.full_messages_for(:receiver_id).each do |message| %>
            <div style="color: crimson"><%= message %></div>
          <% end %>
        </div>
      <%end %>

      <div class="form-group">
        <%= form.label :amount %> <br>
        <%= form.number_field :amount, autofocus: true, class: 'form-control', min:0 %> <br>
        <% @transaction.errors.full_messages_for(:amount).each do |message| %>
          <div style="color: crimson"><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.label :description %> <br>
        <%= form.text_area :description, class: 'form-control'%> <br>
        <% @transaction.errors.full_messages_for(:description).each do |message| %>
          <div  style="color: crimson"><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.hidden_field "role", value: @role %>
        <%= form.hidden_field "tran_type", value: @tran_type %>
        <%= form.submit value:@action, class: 'form-control btn btn-primary rounded submit px-3'%>
      </div>
    <%end %>
  </div>
</div>